language: node_js
node_js:
- 8
addons:
  postgresql: "9.6"
env:
  global:
  - DB_HOST="localhost"
  - DB_NAME="travis_ci_test"
  - DB_USER="postgres"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm run coverage
