db:
  host: DB_HOST
  port: DB_PORT
  database: DB_NAME
  user: DB_USER
  password: DB_PASSWORD
  max: DB_MAX_POOL_SIZE

google-cloud:
  keyFile: GOOGLE_APPLICATION_CREDENTIALS

server:  
  port: SERVER_PORT
  clustering:
    __name: SERVER_CLUSTERING
    __format: json

logging:
  __name: LOGGING
  __format: json