db:
  host: /var/run/postgresql
  port: 5432
  database: database

#see https://cloud.google.com/docs/authentication/getting-started for how to get google application credentials
google-cloud:
  keyFile: service-account-file.json

server:  
  port: 10010
  # If true, the application will be clustered in a number of processes equals to the number of CPU cores
  clustering: true

logging:
  sql:
    console:
      level: info
      colorize: true
  http:
    console:
      level: info
      colorize: true
# You can configure logging that way:
#logging:
#  sql:
#    console:
#      level: warn
#      colorize: true
#    file:
#       level: error
#       timestamp: true
#       filename: logs/sql.log,
#       maxfiles: 5
#       maxsize": 10485760